### ISSUE TITLE
Привет : )

### ISSUE THREAD

**Issue by nikolay-popov** [s-pyadyshev/disciples-site#1]
Дисайплы? Где дисайплы? (почему я здесь)

Что? Что ЭТО? (нифига непонятно, что здесь происходит)

Описаньице в ридмишечке бы, что тут пытаются сделать и как. Ссылочку бы на сайтик потыкать как это будет выглядеть и оценить степень готовности.

Могу помочь : )

**Comment by s-pyadyshev** [comment]
https://s-pyadyshev.github.io/disciples-site/ - потыкать можно тут
А пока нужна помощь в вытягивании остальных картинок
- Качаем программу d2 resource explorer (http://d2ext.sklabs.ru/ru/files)
- Указываем папку с игрой
- Выбираем Imgs/Capital.ff -> ImageMap Structured Data
- Ищем подобные картинки (должны получится картинки зданий на большом прозрачном PNG 640х600) и нажимаем извлечь.
- Называем картинку например elves-temple.png и т.д. (все названия берём из англ. версии)

Буду рад любым предложениям)

**Comment by s-pyadyshev** [comment]
Вытащил картинки, но для эльфов они уже сделаны иначе - их надо редактировать и вручную располагать в нужном месте на прозрачном фоне -_-

**Comment by nikolay-popov** [comment]
Упс, пропустил нотификашку : ( Я на маке, надо посмотреть чем смогу помочь с картинками.
Для понимания - в чем цель проекта? Вы хотите собрать весь визуальный контент?

**Comment by s-pyadyshev** [comment]
Нет никакой цели у проекта, мне просто хотелось сделать "конструктор" замка в браузере =)
Сейчас для помощи с картинками нужен дизайнер. Каждая картинка здания города - это картинка здания на прозрачном фоне 640х600, расположенная в определённом месте. А картинки эльфийских зданий не расположены где нужно на таком же прозрачном фоне.

**Comment by s-pyadyshev** [comment]
closed
